"""Build the publication-safe static site from canonical public tables.

The script reads only tracked, sanitized CSV files under ``results/tables``.
It never reads private run directories or checkpoints.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PROJECT = DOCS / "projects" / "01-quadratic-gpt2"
REPO = "https://github.com/xxlilloxx-cyber/federico-lolli-ai-research"


def rows(path: str) -> list[dict[str, str]]:
    with (ROOT / path).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def shell(title: str, current: str, body: str, description: str = "") -> str:
    items = [
        ("Overview", "index.html", "overview"),
        ("Method", "method.html", "method"),
        ("Experiments", "experiments.html", "experiments"),
        ("Results", "results.html", "results"),
        ("Mechanism", "mechanism.html", "mechanism"),
        ("Comparisons", "comparisons.html", "comparisons"),
        ("Conclusions", "conclusions.html", "conclusions"),
        ("Reproducibility", "reproducibility.html", "reproducibility"),
        ("References", "references.html", "references"),
    ]
    nav = "".join(
        f'<a{(" aria-current=\"page\"" if key == current else "")} href="{href}">{label}</a>'
        for label, href, key in items
    )
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{description}"><title>{title}</title><link rel="stylesheet" href="../../assets/site.css"></head><body>
<header class="site-header"><nav class="nav" aria-label="Site navigation"><a class="brand" href="../../index.html">Federico Lolli<small>AI Research</small></a><div class="nav-links"><a href="../../research/index.html">Projects</a><a href="../../about.html">About</a></div></nav></header><nav class="project-nav" aria-label="Project 01 navigation"><div class="inner">{nav}</div></nav>
<main>{body}</main><footer class="site-footer"><p>Project 01 · Federico Lolli · <a href="mailto:xxlilloxx@gmail.com">xxlilloxx@gmail.com</a></p><p>Original code: <a href="{REPO}/blob/main/LICENSE">MIT</a>. Original text and figures: <a href="{REPO}/blob/main/LICENSE-CONTENT.md">CC BY 4.0</a>. Third-party materials retain their own terms.</p></footer></body></html>'''


def table(headers: list[str], data: list[list[str]], caption: str) -> str:
    head = "".join(f"<th>{x}</th>" for x in headers)
    body = "".join("<tr>" + "".join(f"<td>{x}</td>" for x in row) + "</tr>" for row in data)
    return f'<div class="table-wrap"><table><caption>{caption}</caption><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def figure(src: str, alt: str, caption: str) -> str:
    return f'<figure class="figure"><img src="../../assets/{src}" alt="{alt}"><figcaption>{caption}</figcaption></figure>'


def project_pages() -> dict[str, str]:
    rank = rows("results/tables/rank-confirmation-5000/rank_5000_aggregate.csv")
    ag = rows("results/tables/downstream-ag-news/downstream_controlled_aggregate.csv")
    scaling = rows("results/tables/scaling-ablation/rank_scaling_ablation_aggregate.csv")
    cost = rows("results/tables/computational-cost/computational_cost.csv")
    rank_table = []
    for r in (1, 2, 4, 8):
        l = next(x for x in rank if x["method"] == "LoRA" and int(x["rank"]) == r)
        s = next(x for x in rank if x["method"] == "Symmetric Quadratic" and int(x["rank"]) == r)
        rank_table.append([str(r), f'{float(l["final_validation_loss_mean"]):.4f} ± {float(l["final_validation_loss_sample_sd"]):.4f}', f'{float(s["final_validation_loss_mean"]):.4f} ± {float(s["final_validation_loss_sample_sd"]):.4f}', f'{float(l["final_test_loss_mean"]):.4f} ± {float(l["final_test_loss_sample_sd"]):.4f}', f'{float(s["final_test_loss_mean"]):.4f} ± {float(s["final_test_loss_sample_sd"]):.4f}'])
    ag_table = [["LoRA", f'{float(ag[0]["test_accuracy_mean"]):.4f} ± {float(ag[0]["test_accuracy_sample_sd"]):.4f}', f'{float(ag[0]["test_macro_f1_mean"]):.4f} ± {float(ag[0]["test_macro_f1_sample_sd"]):.4f}'], ["Symmetric Quadratic", f'{float(ag[1]["test_accuracy_mean"]):.4f} ± {float(ag[1]["test_accuracy_sample_sd"]):.4f}', f'{float(ag[1]["test_macro_f1_mean"]):.4f} ± {float(ag[1]["test_macro_f1_sample_sd"]):.4f}']]
    overview = '''<section class="hero"><p class="eyebrow">Research Project 01 · Exploratory controlled study</p><h1>Symmetric Quadratic Adaptation</h1><p class="lede">Can structured quadratic interactions improve the expressive efficiency of low-rank Transformer adaptation under controlled parameter budgets?</p><p>The project keeps GPT-2 frozen and trains small corrections beside selected projections. It compares the linear LoRA baseline with an activation-dependent quadratic branch, then tests rank, placement, training duration, task transfer, scaling, derivatives, and cost.</p><div class="callout good"><strong>Measured outcome.</strong> On the controlled 5,000-step WikiText-2 study, Symmetric had lower mean validation and test loss at ranks 1, 2, 4, and 8. On controlled AG News classification, LoRA had higher mean accuracy and macro-F1. The evidence is task dependent.</div></section>''' + figure("publication/adapter_architecture_comparison.svg", "LoRA and Symmetric Quadratic adapter paths next to a frozen projection.", "<strong>Figure 1.</strong> Both branches use the same number of trainable matrices; Symmetric inserts an element-wise square between its projections.") + '''<section><h2>Evidence at a glance</h2><div class="grid"><article class="card"><h3>Language modelling</h3><p>24 fresh 5,000-step runs: 2 methods × 4 ranks × 3 seeds on WikiText-2.</p></article><article class="card"><h3>Downstream classification</h3><p>Six matched AG News runs, reporting held-out accuracy and macro-F1.</p></article><article class="card"><h3>Mechanism and cost</h3><p>Local Jacobian spectra, adapter Hessians, convergence, and matched rank-4 latency/VRAM.</p></article></div><p><a href="results.html">Read the results</a> · <a href="../../data/TECHNICAL_REPORT.md">Extended technical report</a> · <a href="../../data/SCIENTIFIC_MANUSCRIPT.md">Scientific manuscript</a></p></section>'''
    method = '''<section class="hero compact"><p class="eyebrow">Project 01 · Method</p><h1>Linear and quadratic low-rank corrections</h1><p class="lede">The adapter is a trainable correction to a frozen GPT-2 projection, not a model trained from scratch.</p></section><section><h2>Notation</h2><p>For row activation <code>x ∈ R^(1×d)</code>, frozen weight <code>W ∈ R^(d×d_out)</code>, and frozen bias <code>b</code>, the base projection is:</p><div class="formula">y_base = xW + b</div><p>LoRA and Symmetric use matched trainable shapes:</p><div class="formula">Δy_LoRA = (α/r)(xA)B<br>Δy_Symmetric = (α/r)((xU) ⊙ (xU))P</div><p><code>A,U ∈ R^(d×r)</code> and <code>B,P ∈ R^(r×d_out)</code>. In the controlled rank study, α=4. The effective scales α/r are 4, 2, 1, and 0.5 at ranks 1, 2, 4, and 8.</p><h2>Quadratic structure</h2><div class="formula">Δy_j = (α/r) Σ_k P_kj (xu_k)^2 = xQ_jxᵀ<br>Q_j = (α/r) Σ_k P_kj u_ku_kᵀ</div><p>Each <code>Q_j</code> is symmetric and has rank at most <code>r</code>. Projection directions are shared across outputs; signed coefficients in <code>P</code> can make a particular <code>Q_j</code> indefinite. The expansion <code>(ax₁+bx₂)²=a²x₁²+2abx₁x₂+b²x₂²</code> shows how cross terms arise.</p></section>''' + figure("figures/gpt2-attn-adapter-path.svg", "GPT-2 block showing an adapter parallel to frozen attention c_proj before residual dropout.", "<strong>Figure 2.</strong> The adapter receives the input to <code>attn.c_proj</code>. Frozen projection and adapter outputs are summed before attention residual dropout and the residual addition. Block indices are zero based.")
    experiments = '''<section class="hero compact"><p class="eyebrow">Project 01 · Experiments</p><h1>Campaigns kept separate by protocol</h1><p class="lede">Historical exploration motivated later questions; controlled campaigns provide the central evidence.</p></section><section><h2>Completed campaigns</h2>''' + table(["Campaign", "Design", "Role"], [["Historical adapter families", "LoRA, element-wise/signed quadratic, interaction, Symmetric, Linear+Quadratic; 500/1,000/2,000 steps", "Exploration"], ["Depth and placement", "Attention and MLP screens; full 12-block attention scan", "Placement exploration"], ["Fixed-budget multilayer", "6,144 and 12,288 parameters", "Depth/local-rank evidence"], ["AG News", "2 methods × 3 seeds, 500 steps", "Controlled downstream test"], ["Rank screening", "2 × 4 ranks × 3 seeds, 1,000 steps", "Predeclared screening"], ["Rank confirmation", "24 independent fresh runs, 5,000 steps", "Central controlled result"], ["Scaling ablation", "α=4 versus α/r=1, seed 42", "Single-seed confound check"], ["Mechanism/cost", "Stored checkpoints; fixed held-out activations; matched rank-4 benchmark", "Descriptive structural evidence"]], "Completed evidence only") + '''<h2>Protocol</h2><p>WikiText-2 uses consecutive 128-token blocks and causal cross-entropy. The backbone is frozen GPT-2 Small. Controlled rank runs adapt zero-based block 0 <code>attn.c_proj</code>, use AdamW at 3×10⁻⁴, gradient accumulation 4, α=4, and seeds 42/123/456. Best recorded validation, final step-5,000 validation, and held-out test from that final checkpoint are separate fields. AG News uses the same backbone and placement with a classification head, a fixed 4,096-example train subset, 1,000-example stratified validation subset, and the original test set.</p></section>'''
    results = '''<section class="hero compact"><p class="eyebrow">Project 01 · Results</p><h1>Controlled evidence is task dependent</h1><p class="lede">Values are means ± sample SD across seeds 42, 123, and 456. Lower loss is better; higher accuracy and macro-F1 are better.</p></section><section><h2>5,000-step WikiText-2 confirmation</h2>''' + table(["Rank", "LoRA final val", "Symmetric final val", "LoRA test", "Symmetric test"], rank_table, "Fresh final-checkpoint loss; three seeds") + figure("publication/rank_5000_final_test_loss.svg", "Held-out test loss against rank for LoRA and Symmetric, with seed points and sample SD.", "<strong>Figure 3.</strong> Symmetric has lower mean held-out loss at every tested rank in this configuration. This does not establish universal superiority.") + '''<h2>AG News classification</h2>''' + table(["Method", "Test accuracy", "Test macro-F1"], ag_table, "Held-out AG News; three seeds") + figure("publication/downstream_accuracy_comparison.svg", "AG News test accuracy means, sample SD, and individual seeds.", "<strong>Figure 4.</strong> LoRA is higher on average; all seeds remain visible.") + '''<h2>Single-seed scaling ablation</h2><p>At 1,000 steps, holding α/r=1 retains the sign pattern: rank 1 favours LoRA while ranks 2, 4, and 8 favour Symmetric. At rank 8 the Symmetric-minus-LoRA loss gap changes from −0.1177 with α=4 to −0.0975 at constant effective scale. Because only seed 42 was run, this is exploratory.</p>''' + figure("publication/rank_scaling_ablation_loss.svg", "Seed 42 validation loss by rank under current and constant effective scaling.", "<strong>Figure 5.</strong> Scaling affects magnitude and remains confounded with rank in the main protocol.") + '''<h2>Convergence</h2><p>The independent 1,000-step screen must not be joined to the 5,000-step trajectories. Within the fresh confirmation trajectories, rank 1 initially favours LoRA and crosses between steps 2,000 and 3,000; ranks 2–8 favour Symmetric from the recorded 1,000-step point onward.</p>''' + figure("publication/convergence_rank1.svg", "Fresh rank-1 validation trajectories for LoRA and Symmetric through 5000 steps.", "<strong>Figure 6.</strong> Rank-1 crossover in the independent confirmation campaign; bands are sample SD.") + '''</section>'''
    mechanism = '''<section class="hero compact"><p class="eyebrow">Project 01 · Mechanism</p><h1>Derivatives and learned spectra</h1><p class="lede">These analyses describe what the trained adapters do locally. They do not prove why one method performs better.</p></section><section><h2>Jacobians</h2><div class="formula">J_LoRA = (α/r)AB<br>J_Symmetric(x) = 2(α/r) U diag(xU) P</div><p>LoRA has an input-independent adapter Jacobian. Symmetric has an input-dependent local Jacobian and cannot be represented as one constant ΔW. Analytical derivatives were checked against PyTorch autograd.</p>''' + figure("publication/jacobian_effective_rank.svg", "Entropy effective rank of local adapter Jacobians by rank.", "<strong>Figure 7.</strong> LoRA update rank and Symmetric local-Jacobian rank are related derivative-space quantities, not identical weight objects.") + '''<h2>Second derivatives</h2><p>For a fixed linear output reduction <code>c</code>, Symmetric has:</p><div class="formula">H = 2(α/r) U diag(Pc) Uᵀ</div><p>The LoRA adapter-only Hessian is exactly zero. Symmetric Hessian Frobenius norms are nonzero in trained checkpoints. Because this Hessian is input independent for the exact quadratic adapter and chosen linear reduction, repeated tokens are not treated as independent Hessian observations. A full-block Hessian experiment was not completed and is not reported as a result.</p>''' + figure("publication/adapter_interaction_hessian.svg", "Adapter-only Hessian magnitude summaries for LoRA and Symmetric.", "<strong>Figure 8.</strong> Verified adapter-only second-order response. This is a mathematical and measured structural distinction, not a causal performance explanation.") + '''<h2>Cost at rank 4</h2>''' + table(["Method", "Forward ms", "Backward ms", "Peak VRAM MiB", "Forward tokens/s"], [[x["method"], f'{float(x["forward_ms_mean"]):.3f} ± {float(x["forward_ms_sample_sd"]):.3f}', f'{float(x["backward_ms_mean"]):.3f} ± {float(x["backward_ms_sample_sd"]):.3f}', f'{float(x["peak_vram_mb"]):.2f}', f'{float(x["tokens_per_second_forward"]):.0f}'] for x in cost], "Batch 1, 128 tokens, 10 warm-up and 30 measured iterations") + '''<p>The throughput is about 10.5 <strong>thousand</strong> tokens/s, consistent with 128 tokens divided by roughly 12 ms. Earlier prose that shortened this to 10.5 tokens/s omitted the factor of one thousand.</p></section>'''
    comparisons = '''<section class="hero compact"><p class="eyebrow">Project 01 · Comparisons</p><h1>Relationship to low-rank adaptation research</h1><p class="lede">Methods are compared mathematically and architecturally. Published benchmark numbers from incompatible backbones are not ranked against this study.</p></section><section>''' + table(["Method", "Core mechanism", "Relation"], [["LoRA", "Low-rank weight update BA", "Direct baseline"], ["DoRA", "Separates weight magnitude and direction", "Different weight parameterization"], ["MoRA", "Square trainable matrix with nonparametric transforms", "Higher effective update rank"], ["HiRA", "Hadamard-product high-rank update", "Weight-space higher-rank method"], ["LoRAN", "Nonlinear transform of BA", "Nonlinear weight update, not activation square"], ["PERA", "Polynomial expansion of low-rank factors", "Parameter-space polynomial method"], ["QuadraNet V2", "Factorized quadratic neural layer", "Closest verified quadratic-form precedent; full multi-output equivalence is not established"], ["This study", "(xU)²P beside a frozen projection", "Activation-dependent symmetric quadratic correction"]], "Conceptual comparison; related methods were not experimental baselines") + figure("figures/adapter-family-comparison.svg", "Original schematic comparing LoRA, Symmetric, PERA and QuadraNet V2 mechanisms.", "<strong>Figure 9.</strong> Architectural comparison. Similar terminology does not imply mathematical equivalence.") + '''<p>For one Symmetric output, <code>xᵀU diag(P[:,j])Uᵀx</code> resembles a factorized quadratic form. Across all outputs, the same U directions are shared and P supplies signed output-specific coefficients. The available evidence does not establish complete equivalence to QuadraNet V2. See the <a href="comparisons.html">comparison sources</a> and repository reports for the detailed qualification.</p></section>'''
    conclusions = '''<section class="hero compact"><p class="eyebrow">Project 01 · Conclusions</p><h1>What the evidence supports</h1><p class="lede">Explicit quadratic adaptation is trainable and useful in specific controlled language-model settings, while its benefit is neither task independent nor universal.</p></section><section><h2>Measured</h2><ul><li>Symmetric has lower mean final validation and held-out WikiText-2 loss at ranks 1, 2, 4, and 8 in the 5,000-step block-0 protocol.</li><li>LoRA has higher mean AG News accuracy and macro-F1 under the matched classification protocol.</li><li>The constant-scale check preserves the seed-42 rank sign pattern but changes its magnitude.</li><li>The matched rank-4 latency and memory difference is small on the recorded hardware.</li></ul><h2>Mathematically guaranteed</h2><p>LoRA is linear at the adapter level and has zero adapter-only Hessian. Symmetric is quadratic, has an input-dependent Jacobian, and has a nonzero second derivative when learned factors make the reduced Hessian nonzero.</p><h2>Not established</h2><p>The study does not establish state of the art, statistical significance, transfer to other model families, causal attribution of performance to Hessian magnitude, or mathematical novelty over all prior quadratic networks. Three seeds and two datasets remain a limited evidence base.</p></section>'''
    reproducibility = '''<section class="hero compact"><p class="eyebrow">Project 01 · Reproducibility</p><h1>From evidence to figures</h1><p class="lede">Raw checkpoints stay private; sanitized per-seed tables, configurations, scripts, and provenance are tracked.</p></section><section><h2>Quick verification</h2><div class="formula">git clone https://github.com/xxlilloxx-cyber/federico-lolli-ai-research.git<br>cd federico-lolli-ai-research<br>python -m venv .venv &amp;&amp; . .venv/bin/activate<br>pip install -r requirements.txt<br>PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -q<br>python scripts/validation/validate_public_long_data.py<br>python tools/build_public_site.py</div><p>Plot reproduction uses tracked CSVs and does not require model training. Training commands and private-output locations are documented in <a href="https://github.com/xxlilloxx-cyber/federico-lolli-ai-research/blob/main/research/reproducibility/REPRODUCIBILITY.md">REPRODUCIBILITY.md</a>.</p><h2>Canonical public data</h2><ul><li><a href="../../data/rank_5000_per_seed.csv">rank confirmation per seed</a></li><li><a href="../../data/downstream_controlled_results.csv">AG News per seed</a></li><li><a href="../../data/rank_scaling_ablation_aggregate.csv">scaling ablation</a></li><li><a href="../../data/jacobian_analysis.csv">Jacobian analysis</a></li><li><a href="../../data/computational_cost.csv">cost benchmark</a></li><li><a href="../../data/FIGURE_MANIFEST.csv">figure manifest</a></li></ul><p>Best validation, final validation, and final held-out test remain distinct. Test data did not select method, rank, hyperparameters, or checkpoint.</p></section>'''
    references = '''<section class="hero compact"><p class="eyebrow">Project 01 · References</p><h1>Verified original sources</h1><p class="lede">Related methods provide context and were not experimentally evaluated as baselines unless explicitly stated.</p></section><section><ol class="references"><li>Hu et al. (2022). <a href="https://openreview.net/forum?id=nZeVKeeFYf9">LoRA: Low-Rank Adaptation of Large Language Models</a>. ICLR.</li><li>Liu et al. (2024). <a href="https://proceedings.mlr.press/v235/liu24bn.html">DoRA: Weight-Decomposed Low-Rank Adaptation</a>. ICML.</li><li>Jiang et al. (2024). <a href="https://arxiv.org/abs/2405.12130">MoRA: High-Rank Updating for Parameter-Efficient Fine-Tuning</a>.</li><li>Huang et al. (2025). <a href="https://proceedings.iclr.cc/paper_files/paper/2025/hash/48c368f105e8145b945227b73255635a-Abstract-Conference.html">HiRA: Parameter-Efficient Hadamard High-Rank Adaptation</a>. ICLR.</li><li>Li, Song, and Hou (2024). <a href="https://aclanthology.org/2024.findings-emnlp.177/">LoRAN</a>. Findings of EMNLP.</li><li>Zhang et al. (2026). <a href="https://aclanthology.org/2026.findings-acl.650/">Polynomial Expansion Rank Adaptation</a>. Findings of ACL. DOI 10.18653/v1/2026.findings-acl.650.</li><li>Xu et al. (2026). <a href="https://openaccess.thecvf.com/content/WACV2026/html/Xu_QuadraNet_V2_Efficient_and_Sustainable_Training_of_High-Order_Neural_Networks_WACV_2026_paper.html">QuadraNet V2</a>. WACV.</li><li>Houlsby et al. (2019). <a href="https://proceedings.mlr.press/v97/houlsby19a.html">Parameter-Efficient Transfer Learning for NLP</a>. ICML.</li></ol><p>Full bibliographic metadata and equivalence qualifications are maintained in the repository’s <a href="https://github.com/xxlilloxx-cyber/federico-lolli-ai-research/tree/main/comparisons">comparisons directory</a>.</p></section>'''
    return {"index.html": shell("Project 01 — Symmetric Quadratic Adaptation", "overview", overview), "method.html": shell("Method — Project 01", "method", method), "experiments.html": shell("Experiments — Project 01", "experiments", experiments), "results.html": shell("Results — Project 01", "results", results), "mechanism.html": shell("Mechanism — Project 01", "mechanism", mechanism), "comparisons.html": shell("Comparisons — Project 01", "comparisons", comparisons), "conclusions.html": shell("Conclusions — Project 01", "conclusions", conclusions), "reproducibility.html": shell("Reproducibility — Project 01", "reproducibility", reproducibility), "references.html": shell("References — Project 01", "references", references)}


def main() -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    for name, content in project_pages().items():
        (PROJECT / name).write_text(content + "\n", encoding="utf-8")
    # Stable aliases preserve earlier public URLs.
    for old, target in {"formulation.html": "method.html", "methods.html": "experiments.html", "reproduce.html": "reproducibility.html"}.items():
        (PROJECT / old).write_text(f'<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url={target}"><link rel="canonical" href="{target}"><title>Moved</title><p>This page moved to <a href="{target}">{target}</a>.</p>\n', encoding="utf-8")
    catalog = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Research Projects — Federico Lolli</title><link rel="stylesheet" href="../assets/site.css"></head><body><header class="site-header"><nav class="nav"><a class="brand" href="../index.html">Federico Lolli<small>AI Research</small></a><div class="nav-links"><a href="../index.html">Home</a><a aria-current="page" href="index.html">Research projects</a><a href="../about.html">About &amp; contact</a></div></nav></header><main><section class="hero compact"><p class="eyebrow">Research projects</p><h1>Studies in this archive</h1><p class="lede">Projects are added only when their source material, completed evidence, and limitations can be presented clearly.</p></section><section><div class="grid two"><article class="card"><p class="project-number">RESEARCH PROJECT 01</p><h2>Symmetric Quadratic Adaptation</h2><p>Controlled experiments compare frozen-backbone LoRA with an activation-dependent quadratic adapter on WikiText-2 and AG News, followed by rank, scaling, mechanism, and cost analyses.</p><p><a href="../projects/01-quadratic-gpt2/index.html">Project overview →</a></p></article></div></section></main><footer class="site-footer">© Federico Lolli · <a href="mailto:xxlilloxx@gmail.com">xxlilloxx@gmail.com</a></footer></body></html>'''
    (DOCS / "research" / "index.html").write_text(catalog + "\n", encoding="utf-8")
    print(f"built {len(project_pages())} Project 01 pages and 3 compatibility aliases")


if __name__ == "__main__":
    main()
